version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    EKS_CLUSTER_NAME: "pulsecare-dev"
    MONITORING_RELEASE: "pulsecare-monitoring"

phases:
  install:
    commands:
      - set -e
      - echo "Installing kubectl"
      - curl -sSLo kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.0/2024-05-12/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - kubectl version --client
      - echo "Installing helm"
      - curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - helm version

  pre_build:
    commands:
      - set -e
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
      - kubectl get nodes
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      - helm repo update

  build:
    commands:
      - |
        set -e
        helm upgrade --install "$MONITORING_RELEASE" prometheus-community/kube-prometheus-stack \
          --namespace default \
          --values deploy/helm/monitoring-values.yaml \
          --wait \
          --timeout 10m

        kubectl apply -f deploy/k8s/default/config.yaml
        kubectl apply -f deploy/k8s/default/postgres.yaml
        kubectl apply -f deploy/k8s/default/redis.yaml
        kubectl rollout status deployment/postgres --timeout=240s
        kubectl rollout status deployment/redis --timeout=180s

        kubectl apply -f deploy/k8s/default/alert-service.yaml
        kubectl apply -f deploy/k8s/default/risk-scoring-service.yaml
        kubectl apply -f deploy/k8s/default/ingestion-service.yaml
        kubectl apply -f deploy/k8s/default/device-simulator.yaml

        kubectl rollout restart deployment/alert-service
        kubectl rollout restart deployment/risk-scoring-service
        kubectl rollout restart deployment/ingestion-service
        kubectl rollout restart deployment/device-simulator

        kubectl rollout status deployment/alert-service --timeout=240s
        kubectl rollout status deployment/risk-scoring-service --timeout=240s
        kubectl rollout status deployment/ingestion-service --timeout=240s
        kubectl rollout status deployment/device-simulator --timeout=240s
        kubectl apply -f deploy/k8s/monitoring/service-monitors.yaml

  post_build:
    commands:
      - kubectl get pods
      - kubectl get svc
      - kubectl get servicemonitor
