apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.deviceSimulator.name }}
spec:
  replicas: {{ .Values.services.deviceSimulator.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.deviceSimulator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.deviceSimulator.name }}
    spec:
      containers:
        - name: {{ .Values.services.deviceSimulator.name }}
          image: {{ include "pulsecare.image" (dict "root" . "repository" .Values.services.deviceSimulator.repository) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DEVICE_COUNT
              valueFrom:
                configMapKeyRef:
                  name: pulsecare-app-config
                  key: DEVICE_COUNT
            - name: SEND_INTERVAL_MS
              valueFrom:
                configMapKeyRef:
                  name: pulsecare-app-config
                  key: SEND_INTERVAL_MS
            - name: ERROR_MODE
              valueFrom:
                configMapKeyRef:
                  name: pulsecare-app-config
                  key: ERROR_MODE
            - name: TARGET_INGESTION_URL
              valueFrom:
                configMapKeyRef:
                  name: pulsecare-app-config
                  key: TARGET_INGESTION_URL
            - name: REGION_COUNT
              valueFrom:
                configMapKeyRef:
                  name: pulsecare-app-config
                  key: REGION_COUNT
            - name: SCENARIO_NAME
              valueFrom:
                configMapKeyRef:
                  name: pulsecare-app-config
                  key: SCENARIO_NAME
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.deviceSimulator.name }}
  labels:
    app: {{ .Values.services.deviceSimulator.name }}
spec:
  selector:
    app: {{ .Values.services.deviceSimulator.name }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
