{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pulsecare-services
  labels:
    release: {{ .Values.serviceMonitor.releaseLabel }}
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ .Values.services.ingestion.name }}
          - {{ .Values.services.riskScoring.name }}
          - {{ .Values.services.alert.name }}
          - {{ .Values.services.deviceSimulator.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
